version: "3.5"
services:
  database_master:
    image: mysql:8.0.30
    container_name: "database_master"
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./confs/master.sql:docker-entrypoint-initdb.d/init.sql
      - mysqldata_master:/var/lib/mysql
      - ./master.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=mysql_user
      - MYSQL_DATABASE=inventario_escuelas
      - MYSQL_PASSWORD=password
    networks:
      - mynetwork
  database_slave:
    image: mysql:8.0.30
    container_name: "database_slave"
    restart: unless-stopped
    depends_on:
      - database_master
    ports:
      - 3307:3306
    volumes:
      - ./confs/slave.sql:docker-entrypoint-initdb.d/init.sql
      - mysqldata_slave:/var/lib/mysql
      - ./slave.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=mysql_user
      - MYSQL_DATABASE=inventario_escuelas
      - MYSQL_PASSWORD=password
    networks:
      - mynetwork
networks:
  mynetwork:
volumes:
  mysqldata_master:
  mysqldata_slave:
